In [2]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Data Cleaning and Preprocessing

In [6]:
df = pd.read_csv("pima_data - Copy.csv")

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,192,66,35,64,31.3,1.668,42,1
1,3,122,56,44,269,42.1,0.562,41,0
2,12,126,99,48,163,18.7,0.810,46,1
3,14,108,103,27,290,26.6,1.587,60,1
4,10,178,74,48,186,34.6,1.539,41,1

In [5]:
# No null values, all numerical types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
df.shape

(768, 9)

In [9]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,6.875000,132.734375,78.796875,33.065104,154.665365,34.554818,1.260259,50.032552,0.769531
std,4.364429,37.549234,23.548344,15.028818,81.667825,9.019027,0.702278,16.981629,0.421407
min,0.000000,70.000000,40.000000,7.000000,15.000000,18.100000,0.100000,21.000000,0.000000
25%,3.000000,102.000000,59.000000,20.000000,82.000000,27.250000,0.642000,36.000000,1.000000
50%,7.000000,131.000000,77.000000,32.000000,155.000000,34.950000,1.234000,49.000000,1.000000
75%,11.000000,166.000000,99.250000,46.000000,224.000000,42.100000,1.883500,65.000000,1.000000
max,14.000000,199.000000,119.000000,59.000000,299.000000,49.900000,2.494000,79.000000,1.000000

In [30]:
# Checking for invalid zeros in any columns using 
# Code from ChatGPT
# zeros in Pregnancies and Outcome columns make sense so I'll keep them
(df == 0).any()

Pregnancies                  True
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                      True
dtype: bool

In [32]:
X = df.drop(["Outcome"], axis=1)
y = df["Outcome"]

X.shape, y.shape

((768, 8), (768,))

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((614, 8), (614,), (154, 8), (154,))

# Creating Models and applying scaling

In [43]:
scaler = StandardScaler()

In [ ]:
rf_param_grid = {
'n_estimators': [100, 200, 300],
'max_depth': [5, 10, 15]
}
lr_param_grid = {
'C': [0.1, 1, 10]
}
svm_param_grid = {
'kernel': ['linear', 'rbf'],
'C': [0.1, 1, 10],
'gamma': [0.01, 0.1, 1]
}
knn_param_grid = {
'n_neighbors': [3, 5, 7, 9, 11]
}